name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - artifact-name: Build - Ubuntu
            os: ubuntu-latest
          - artifact-name: Build - macOS
            os: macOS-latest
    
    name: ${{ matrix.artifact-name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            -PmvnUsername=${{ secrets.TRAJOPT_MAVEN_USERNAME }}
            -PmvnPassword=${{ secrets.TRAJOPT_MAVEN_PASSWORD }}
